services:
  - type: web
    name: ryxide-backend-terminal
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18
